version: '2'
services:
  web:
    build: .
    volumes:
       - /home/phoenix-log-monitor/:/app/
    command: 
       - /app/post_script.sh
    ports:
      - "5000:5000"
      - "9001:9001"
  # node:
  #   image: node
  #   volumes:
  #     - .:/app
    
  #   ports:
  #     - "9001:9001"